name: sandbox
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  sandboxed_core: ^0.1.0
  sandboxed: ^0.1.0

  draggable_route: 
    path: ../../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Code Generator
  build_runner: ^2.0.0
  sandboxed_generator: ^0.1.0


flutter:
  uses-material-design: true
